name: Build Karing Android APK

on:
  workflow_dispatch: # မိမိဘာသာ Manual နှိပ်ပြီး Build ရန်အတွက်

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive # V2Ray Core များ ပါဝင်လာစေရန်

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    -  name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.29.0' # Flutter version အသစ်သို့ ပြောင်းလဲခြင်း
            channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Debug APK
      run: flutter build apk --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: M-Gate-VPN-APK
        path: build/app/outputs/flutter-apk/app-debug.apk
